# This file lists the dependencies needed to build and test all of flatsurvey.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: flatsurvey
channels:
  - flatsurf
  - conda-forge
  - defaults
dependencies:
  - sage-flatsurf >=0.4
  - pyflatsurf
  - pyintervalxt
  - click
  - pip
  - pytest
  - pytest-xdist
  - plumbum
  - python-dateutil
  - boto3
  - moto
  - ruamel.yaml
  - pip:
    - pinject
    - gql==3.0.0a6
    - aioresponses
