# This file lists the dependencies needed to build and test all of flatsurvey.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: flatsurvey
channels:
  - conda-forge
dependencies:
  - black >=22,<23
  - click
  - dask
  - humanfriendly
  - isort
  - more-itertools
  - pip
  - psutil
  - pyflatsurf
  - pyintervalxt
  - pylint
  - pytest
  - pytest-xdist
  - python-dateutil
  - rich
  - ruamel.yaml
  - sage-flatsurf >=0.5.2,<0.6
  - pip:
    - pinject
