# This file lists the dependencies needed to build and test all of flatsurvey.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: flatsurvey
channels:
  - flatsurf
  - conda-forge
  - defaults
dependencies:
  - black >=22,<23
  - boto3
  - click
  - isort
  - moto
  - pip
  - pyflatsurf
  - pyintervalxt
  - pylint
  - pytest
  - pytest-xdist
  - python-dateutil
  - ruamel.yaml
  - sage-flatsurf >=0.4.4
  - pip:
    - aioresponses
    - gql==3.0.0a6
    - pinject
