service: flatsurvey-data-store-api

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  memorySize: 2048
  versionFunctions: true
  apiKeys:
    - postgraphile-dev-apikey
  vpc:
    securityGroupIds:
      - sg-93f761ee
    subnetIds:
      - subnet-4a15c806
      - subnet-c4e628b8
      - subnet-e19c0f8b

plugins:
  - serverless-express
  - serverless-dotenv-plugin

functions:
  graphql:
    handler: api.handler
    timeout: 60
    events:
      - http:
          path: /
          method: POST
