service: flatsurvey-data-store-migration

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  memorySize: 2048
  timeout: 900
  versionFunctions: true
  apiKeys:
    - flatsurvey-data-store-migration-api-key
  vpc:
    securityGroupIds:
      - sg-93f761ee
    subnetIds:
      - subnet-4a15c806
      - subnet-c4e628b8
      - subnet-e19c0f8b

custom:
  dotenv:
    logging: false

plugins:
  - serverless-dotenv-plugin

functions:
  migrate:
    handler: migration.handler
  dump-schema:
    handler: schema.handler
